# Generated by Django 5.0.4 on 2024-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='v1',
        ),
        migrations.RemoveField(
            model_name='react',
            name='employee',
        ),
        migrations.AddField(
            model_name='react',
            name='v2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='v3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='v4',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='v5',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
